name: Publish DEB Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip debhelper dpkg-dev

    - name: Fix permissions
      run: chmod 755 debian/DEBIAN/postinst

    - name: Build DEB package
      run: dpkg-deb --build debian portip.deb

    - name: Upload DEB package as artifact
      uses: actions/upload-artifact@v2
      with:
        name: portip-deb
        path: portip.deb

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: "PortIP v1.0.0"
        body: "Initial release of PortIP tool"
        draft: false
        prerelease: false

    - name: Upload DEB to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./portip.deb
        asset_name: portip.deb
        asset_content_type: application/octet-stream
